name: Hello World v2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  informations:
    runs-on: ubuntu-latest
    steps:
      - name: Qui a déclenché ce workflow ?
        run: echo "Déclenché par : ${{ github.actor }}"
        
      - name: Sur quelle branche ?
        run: echo "Branche : ${{ github.ref_name }}"
        
      - name: Quel événement ?
        run: echo "Événement : ${{ github.event_name }}"
        
      - name: Numéro du run
        run: echo "Run numéro : ${{ github.run_number }}"
