name: Hello World v2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  informations:
    runs-on: ubuntu-latest
    steps:
      - name: Afficher les variables système
        run: |
          echo "actor  ${{ github.actor }}"
          echo "repository  ${{ github.repository }}"
          echo "sha  ${{ github.sha }}"
          echo "ref  ${{ github.ref }}"
          echo "event_name  ${{ github.event_name }}"
          echo "run_id  ${{ github.run_id }}"
          echo "run_number  ${{ github.run_number }}"
          echo "workspace  ${{ github.workspace }}"
      - name: Qui a déclenché ce workflow ?
        run: |
          echo "Déclenché par : ${{ github.actor }}"
